/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package combination;

import Common.MainMenu;
import Common.Values;

/**
 *
 * @author Lescoffit
 */
public class CombinationMainf extends javax.swing.JFrame {

    /**
     * Creates new form CombinationMainf
     */
    public CombinationMainf() {
        setVisible(true);
        setTitle("Combination");
        initComponents();
        Values.Framestate = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AttackbuttonC = new javax.swing.JButton();
        DefendButtonC = new javax.swing.JButton();
        VersusButtonC = new javax.swing.JButton();
        MainMenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AttackbuttonC.setText("Attack");
        AttackbuttonC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AttackbuttonCMouseClicked(evt);
            }
        });

        DefendButtonC.setText("Defend");
        DefendButtonC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DefendButtonCMouseClicked(evt);
            }
        });

        VersusButtonC.setText("Versus");
        VersusButtonC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VersusButtonCMouseClicked(evt);
            }
        });

        MainMenuButton.setText("MainMenu");
        MainMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainMenuButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VersusButtonC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DefendButtonC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AttackbuttonC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(AttackbuttonC)
                .addGap(71, 71, 71)
                .addComponent(DefendButtonC)
                .addGap(80, 80, 80)
                .addComponent(VersusButtonC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(MainMenuButton)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AttackbuttonCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttackbuttonCMouseClicked
        new CombinationAttack();
        this.setVisible(false);
    }//GEN-LAST:event_AttackbuttonCMouseClicked

    private void DefendButtonCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DefendButtonCMouseClicked
        new CombinationDefend();
        this.setVisible(false);
    }//GEN-LAST:event_DefendButtonCMouseClicked

    private void VersusButtonCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VersusButtonCMouseClicked
        new CombinationVersus();
        this.setVisible(false);
    }//GEN-LAST:event_VersusButtonCMouseClicked

    private void MainMenuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainMenuButtonMouseClicked
        this.setVisible(false);
        new MainMenu();
    }//GEN-LAST:event_MainMenuButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AttackbuttonC;
    private javax.swing.JButton DefendButtonC;
    private javax.swing.JButton MainMenuButton;
    private javax.swing.JButton VersusButtonC;
    // End of variables declaration//GEN-END:variables

}
